ConsultaCep/Models/Consulta.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ConsultaCep.Models
{
    public class Consulta
    {
        public Root Root { get; set; }
    }
}

ConsultaCep/Models/Context.cs
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ConsultaCep.Models
{
    public class Context : DbContext
    {
        public Context(DbContextOptions<Context> options) : base(options) 
        { 

        }
        public DbSet<Root> Roots { get; set; }
    }
}

ConsultaCep/Models/Dados.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ConsultaCep.Models
{
    public class Dados
    {
        public string Cep { get; set; }
        public string Logradouro { get; set; }
        public string Complemento { get; set; }
        public string Bairro { get; set; }
        public string Localidade { get; set; }
        public string Uf { get; set; }

    }
}

ConsultaCep/Models/Root.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace ConsultaCep.Models
{
    [Table("ConsultaCEP")]
    public class Root
    {
            [Key]
            public int ConsultaId { get; set; }
            public string Cep { get; set; }
            public string Logradouro { get; set; }
            public string Complemento { get; set; }
            public string Bairro { get; set; }
            public string Localidade { get; set; }
            public string Uf { get; set; }
        
    }
}

ConsultaCep/Controllers/ConsultaAPIController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ConsultaCep.DAL;
using ConsultaCep.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace ConsultaCep.Controllers
{
    [Route("api/Endereco")]
    [ApiController]
    public class ConsultaAPIController : ControllerBase
    {
        private readonly ConsultaDAO _consultaDAO;
        public ConsultaAPIController(ConsultaDAO consultaDAO)
        {
            _consultaDAO = consultaDAO;
        }

        // GET: /api/Endereco/ListarEnderecos
        [HttpGet]
        [Route("ListarEnderecos")]
        public IActionResult Listar()
        {
            return Ok(_consultaDAO.Listar());
        }

        // POST: /api/Endereco/CadastrarEndereco
        [HttpPost]
        [Route("CadastrarEndereco")]
        public IActionResult Cadastrar(Root consulta)
        {
            _consultaDAO.Cadastrar(consulta);
            return Created("", consulta);
        }

        // PUT: api/Endereco/AlterarEndereco
        [HttpPut("{id}")]
        [Route("AlterarEndereco")]
        public IActionResult Alterar (int id, Root consulta)
        {
            if (id != consulta.ConsultaId)
            {
                return BadRequest();
            }
                _consultaDAO.Alterar(id, consulta);
                return NoContent();
        }

        // DELETE: api/DeletarEndereco/
        [HttpDelete]
        [Route("DeletarEndereco")]
        public IActionResult Deletar (int id)
        {
            _consultaDAO.Deletar(id);
            return NoContent();
        }

    }
}

ConsultaCep/Controllers/ConsultaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using ConsultaCep.DAL;
using ConsultaCep.Models;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

//Alexandra Naomi Sakaguchi

namespace ConsultaCep.Controllers
{
    public class ConsultaController : Controller
    {
        private readonly ConsultaDAO _consultaDAO;
        public ConsultaController(ConsultaDAO consultaDAO)
        {
            _consultaDAO = consultaDAO; 
        }
        public IActionResult Index()
        {
            if(TempData["Cep"] != null)
            {
                string resultado = TempData["Cep"].ToString();
                Root consulta = JsonConvert.DeserializeObject<Root>(resultado);
                _consultaDAO.Cadastrar(consulta);
                return View(consulta);
            }
            return View();
        }

        [HttpPost]
        public IActionResult PesquisarCep(string txtCep)
        {
            string url = $@"https://viacep.com.br/ws/{txtCep}/json/";
            WebClient cliente = new WebClient();
            TempData["Cep"] = cliente.DownloadString(url);
            return RedirectToAction("Index");
        }
    }
}

ConsultaCep/Views/Consulta/Index.cshtml
@model Root
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <title>Consultar e Cadastrar CEP</title>
</head>
<body>

    <h4>Consultar e Cadastrar CEP</h4>
    <div class="container" style="margin-top:30px">
        <form asp-action="PesquisarCep" asp-controller="Consulta">
            <input type="submit" value="Consultar e Cadastrar" class="btn btn-info" /> <br /><br />
            <b><label for="txtCep">CEP</label></b>
            <input type="text" id="txtCep" class="form-control col-4" name="txtCep" />

        </form><br />
    </div>
    <table class="table">
        <thead>
            <tr>
                <th scope="col">CEP</th>
                <th scope="col">Logradouro</th>
                <th scope="col">Complemento</th>
                <th scope="col">Bairro</th>
                <th scope="col">Localidade</th>
                <th scope="col">UF</th>
            </tr>
        </thead>

        <tbody>
            <tr>
                <td><input type="text" asp-for="Cep" disabled/></td>
                <td><input type="text" asp-for="Logradouro" disabled /></td>
                <td><input type="text" asp-for="Complemento" disabled/></td>
                <td><input type="text" asp-for="Bairro" disabled/></td>
                <td><input type="text" asp-for="Localidade" disabled/></td>
                <td><input type="text" asp-for="Uf" disabled /></td>

            </tr>
        </tbody>
    </table>
</body>
</html>